apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: gleybernet/demo-app:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "Demo App Kubernetes"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"