name: CI - Build Demo App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Ler versão do arquivo VERSION
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Versão detectada: $VERSION"

      - name: Build da imagem Docker
        run: |
          docker build -t demo-app:${{ steps.version.outputs.version }} .
          docker images | grep demo-app